local keySet = vim.keymap.set

-- fuzzy find (requires ibhagwan/fzf-lua)
keySet("n", "<leader>bl", "<cmd>FzfLua blines<cr>", { desc = "Fuzzy find - Buffer lines" })
keySet("n", "<leader>bg", "<cmd>FzfLua grep_curbuf<cr>", { desc = "Fuzzy find - Buffer grep" })
keySet("n", "<leader>f:", "<cmd>FzfLua<cr>", { desc = "Fuzzy find - fzf commands" })
keySet("n", "<leader>fr", "<cmd>FzfLua resume<cr>", { desc = "Fuzzy find - resume search" })
keySet("n", "<leader>fh", "<cmd>FzfLua helptags<cr>", { desc = "Fuzzy find - help tags" })
keySet("n", "<leader>fm", "<cmd>FzfLua manpages<cr>", { desc = "Fuzzy find - man pages" })
keySet("n", "<leader>fk", "<cmd>FzfLua keymaps<cr>", { desc = "Fuzzy find - keymaps" })
keySet("n", "<leader>ff", "<cmd>FzfLua files<cr>", { desc = "Fuzzy find - files in current working directory" })
keySet("n", "<leader>fb", "<cmd>FzfLua buffers<cr>", { desc = "Fuzzy find - open buffers" })
keySet("n", "<leader>fg", "<cmd>FzfLua live_grep_glob<cr>", { desc = "Fuzzy find - grep globally" })
keySet("n", "<leader>ft", "<cmd>FzfLua tabs<cr>", { desc = "Fuzzy Find - tabs" })

-- undotree (requires mbbill/undotree)
keySet("n", "<leader>u", "<cmd>UndotreeToggle<cr>", { desc = "Undotree Toggle" })

-- LSP (requires stuff in lsp.lua and fzf-lua)
keySet("n", "<leader>gsd", "<cmd>FzfLua lsp_definitions<cr>", { desc = "Search definitions" })
keySet("n", "<leader>gsD", "<cmd>FzfLua lsp_declarations<cr>", { desc = "Search declarations" })
keySet("n", "<leader>gsi", "<cmd>FzfLua lsp_implementations<cr>", { desc = "Search implementations" })
keySet("n", "<leader>gsr", "<cmd>FzfLua lsp_references<cr>", { desc = "Search references" })
keySet("n", "<leader>gsa", "<cmd>FzfLua lsp_code_actions<cr>", { desc = "Search code actions" })
keySet("n", "<leader>gsk", "<cmd>FzfLua diagnostics_document<cr>", { desc = "Search diagnostics" })
keySet("n", "<leader>gsK", "<cmd>FzfLua diagnostics_workspace<cr>", { desc = "Search diagnostics (workspace)" })

-- mason (requires mason-org/mason.nvim)
keySet("n", "<leader>M", "<cmd>Mason<cr>", { desc = "Open Mason menu" })

-- obsidian (requires obsidian/obsidian.nvim)
keySet("n", "<leader>on", "<cmd>ObsidianQuickSwitch<cr>", { desc = "Obsidian - switch notes" })
keySet("n", "<leader>ow", "<cmd>ObsidianWorkspace<cr>", { desc = "Obsidian - switch workspaces" })
keySet("n", "<leader>ot", "<cmd>ObsidianTags<cr>", { desc = "Obsidian - search tags" })
keySet("n", "<leader>oa", "<cmd>ObsidianTOC<cr>", { desc = "Obsidian - search headings" })
keySet("n", "<leader>ol", "<cmd>ObsidianLinks<cr>", { desc = "Obsidian - search links" })
keySet("n", "<leader>ob", "<cmd>ObsidianBacklinks<cr>", { desc = "Obsidian - search backlinks" })
keySet("n", "<leader>og", "<cmd>ObsidianSearch<cr>", { desc = "Obsidian - grep workspace" })
keySet("n", "<leader>op", "<cmd>ObsidianPasteImg<cr>", { desc = "Obsidian - paste image" })
keySet("n", "<leader>orr", "<cmd>ObsidianRename<cr>", { desc = "Obsidian - rename current file" })
